from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from app.core.config import get_settings
from app.db.base import Base
from app.models import *  # noqa: F401,F403 - populates Base.metadata for autogenerate

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Single source of truth for the DB URL: app settings (.env), not a
# separate sqlalchemy.url line in alembic.ini that could drift from it.
config.set_main_option("sqlalchemy.url", get_settings().database_url)

target_metadata = Base.metadata


def _add_custom_type_imports(context_, revision, directives) -> None:
    """Autogenerate renders EncryptedString columns as
    `app.core.security.EncryptedString(...)` (it's not a plain sqlalchemy
    type, so the default renderer can't infer an import for it) — without
    this hook every autogenerated migration touching a PHI column fails at
    upgrade time with `NameError: name 'app' is not defined`.
    """
    for script in directives:
        if script.upgrade_ops.is_empty():
            continue
        script.imports.add("import app.core.security")


def run_migrations_offline() -> None:
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        process_revision_directives=_add_custom_type_imports,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            process_revision_directives=_add_custom_type_imports,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
