"""initial schema

Revision ID: 12b40b94de66
Revises: 
Create Date: 2026-08-18 19:40:57.722753

"""
from alembic import op
import sqlalchemy as sa
import app.core.security

# revision identifiers, used by Alembic.
revision = '12b40b94de66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinicians',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('prc_license_number', sa.String(length=64), nullable=True),
    sa.Column('mfa_secret', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinicians_email'), 'clinicians', ['email'], unique=True)
    op.create_table('patients',
    sa.Column('full_name', app.core.security.EncryptedString(length=512), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_birthdate'), 'patients', ['birthdate'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_clinician_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('diff', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_clinician_id'], ['clinicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encounters',
    sa.Column('patient_id', sa.String(length=36), nullable=True),
    sa.Column('clinician_id', sa.String(length=36), nullable=False),
    sa.Column('upload_idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('audio_object_key', sa.String(length=512), nullable=True),
    sa.Column('audio_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('audio_retention_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pipeline_status', sa.String(length=32), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinician_id'], ['clinicians.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounters_patient_id'), 'encounters', ['patient_id'], unique=False)
    op.create_index(op.f('ix_encounters_upload_idempotency_key'), 'encounters', ['upload_idempotency_key'], unique=True)
    op.create_table('consent_ledger_entries',
    sa.Column('encounter_id', sa.String(length=36), nullable=False),
    sa.Column('event', sa.String(length=16), nullable=False),
    sa.Column('participant_roster', sa.String(length=2048), nullable=False),
    sa.Column('purposes', sa.String(length=512), nullable=False),
    sa.Column('script_language', sa.String(length=8), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_ledger_entries_encounter_id'), 'consent_ledger_entries', ['encounter_id'], unique=False)
    op.create_table('notes',
    sa.Column('encounter_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('GENERATED', 'FILED', 'AUTHENTICATED', 'SIGNED', name='notestatus', native_enum=False), nullable=False),
    sa.Column('assessment', app.core.security.EncryptedString(length=4096), nullable=False),
    sa.Column('plan', app.core.security.EncryptedString(length=4096), nullable=False),
    sa.Column('subjective', app.core.security.EncryptedString(length=4096), nullable=False),
    sa.Column('objective', app.core.security.EncryptedString(length=4096), nullable=False),
    sa.Column('source_spans', sa.Text(), nullable=False),
    sa.Column('note_generator_provider', sa.String(length=16), nullable=False),
    sa.Column('signed_by_clinician_id', sa.String(length=36), nullable=True),
    sa.Column('signed_prc_license_number', sa.String(length=64), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['signed_by_clinician_id'], ['clinicians.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('encounter_id')
    )
    op.create_table('note_revisions',
    sa.Column('note_id', sa.String(length=36), nullable=False),
    sa.Column('section', sa.String(length=16), nullable=False),
    sa.Column('previous_text', app.core.security.EncryptedString(length=4096), nullable=False),
    sa.Column('new_text', app.core.security.EncryptedString(length=4096), nullable=False),
    sa.Column('edited_by_clinician_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['edited_by_clinician_id'], ['clinicians.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_revisions_note_id'), 'note_revisions', ['note_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_revisions_note_id'), table_name='note_revisions')
    op.drop_table('note_revisions')
    op.drop_table('notes')
    op.drop_index(op.f('ix_consent_ledger_entries_encounter_id'), table_name='consent_ledger_entries')
    op.drop_table('consent_ledger_entries')
    op.drop_index(op.f('ix_encounters_upload_idempotency_key'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_patient_id'), table_name='encounters')
    op.drop_table('encounters')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_patients_birthdate'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_clinicians_email'), table_name='clinicians')
    op.drop_table('clinicians')
    # ### end Alembic commands ###
