"""Phase 6: pilot instrumentation tables.

Two tables that deliberately hold **no PHI** -- similarity ratios, star
counts, durations and ids -- so a pilot report is readable by whoever
decides go/no-go without giving them clinical access, and so these rows can
outlive the notes they describe. Phase 4.4's retention purge deletes note
revisions long before a pilot is assessed; a metric that still depended on
them would quietly become uncomputable partway through.

Both CHECK constraints are the point rather than decoration. A similarity
outside [0, 1] means the computation is broken, and a broken metric that
still writes rows is worse than one that fails -- it produces a plausible
pilot verdict out of nonsense. Stars outside 1-5 is the same argument for
the satisfaction score.

Revision ID: 6d6367a508f0
Revises: b1c2d3e4f5a6
Create Date: 2026-08-29 13:06:37.453948

"""
from alembic import op
import sqlalchemy as sa
import app.core.security

# revision identifiers, used by Alembic.
revision = '6d6367a508f0'
down_revision = 'b1c2d3e4f5a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encounter_ratings',
    sa.Column('encounter_id', sa.String(length=36), nullable=False),
    sa.Column('clinician_id', sa.String(length=36), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('comment', app.core.security.EncryptedString(length=2048), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('stars >= 1 AND stars <= 5', name='ck_encounter_rating_stars'),
    sa.ForeignKeyConstraint(['clinician_id'], ['clinicians.id'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('encounter_id', name='uq_encounter_rating_encounter')
    )
    op.create_index(op.f('ix_encounter_ratings_clinician_id'), 'encounter_ratings', ['clinician_id'], unique=False)
    op.create_index(op.f('ix_encounter_ratings_encounter_id'), 'encounter_ratings', ['encounter_id'], unique=False)
    op.create_table('note_quality_metrics',
    sa.Column('note_id', sa.String(length=36), nullable=False),
    sa.Column('definition_version', sa.String(length=32), nullable=False),
    sa.Column('minor_only', sa.Boolean(), nullable=False),
    sa.Column('mean_similarity', sa.Float(), nullable=False),
    sa.Column('safety_flagged_sections', sa.String(length=128), nullable=False),
    sa.Column('per_section_json', sa.Text(), nullable=False),
    sa.Column('reconstruction_ambiguous', sa.Boolean(), nullable=False),
    sa.Column('total_seconds', sa.Integer(), nullable=True),
    sa.Column('review_seconds', sa.Integer(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_by_clinician_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('mean_similarity >= 0.0 AND mean_similarity <= 1.0', name='ck_note_quality_similarity_range'),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['signed_by_clinician_id'], ['clinicians.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_id', 'definition_version', name='uq_note_quality_note_definition')
    )
    op.create_index(op.f('ix_note_quality_metrics_note_id'), 'note_quality_metrics', ['note_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_quality_metrics_note_id'), table_name='note_quality_metrics')
    op.drop_table('note_quality_metrics')
    op.drop_index(op.f('ix_encounter_ratings_encounter_id'), table_name='encounter_ratings')
    op.drop_index(op.f('ix_encounter_ratings_clinician_id'), table_name='encounter_ratings')
    op.drop_table('encounter_ratings')
    # ### end Alembic commands ###
